# action.yml
name: 'Create PDF from MkDocs'
description: 'Builds a PDF for MkDocs a site'
author: 'Tim Sutton, tim@kartoza.com'
branding:
  icon: 'arrow-up-circle'  
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
